core/urls.py
from django.conf.urls import url
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
]

tunes_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^albums/$', views.album_list, name='album_list'),
    url(r'^artists/$', views.artist_list, name='artist_list'),
    url(r'^genres/$', views.genre_list, name='genre_list'),
    url(r'^albums/(?P<id>\d+)/$', views.album_detail, name='album_detail'),
    url(r'^artists/(?P<id>\d+)/$', views.artist_detail, name='artist_detail'),
]

tunes_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
#    url(r'^album/', include('tunes_app.urls', namespace='album')),
#    url(r'^artist/', include('tunes_app.urls', namespace='artist')),
#    url(r'^genre/', include('tunes_app.urls', namespace='genre')),
    url(r'^music/', include('tunes_app.urls', namespace='music')),
    url(r'^', include('core.urls', namespace='core')),
]

core/models.py
from django.db import models

# Create your models here.

tunes_app/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
    name = models.CharField(max_length=50)
    artist = models.ForeignKey('Artist')
    genre = models.ForeignKey('Genre')

    def __str__(self):
        return self.name

    def get_artist_names(self):
        artist_names = [artist.name for artist in self.artist.all()]
        return " ".join(artist_names)

    def get_absolute_url(self):
        return reverse('tunes_app:album_detail', args=[self.pk])

class Track(models.Model):
    name = models.CharField(max_length=50)
    album = models.ForeignKey('Album')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        #return reverse('namespace:name', args=[self.pk])
        pass

class Artist(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Genre(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

core/views.py
from django.shortcuts import render


def index(request):
    return render(request, "core/index.html")

tunes_app/views.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.db.models import Count
from django.http import HttpResponse

from .models import Album, Track, Artist, Genre

def album_list(request):
    albums = Album.objects.all()

    context = {
        "albums": albums,
    }
    return render(request, "tunes_app/album_list.html", context)

def artist_detail(request, id):
    specific_artist = get_object_or_404(Artist, pk=id)
    artist_albums = specific_artist.album_set.all()

    context = {
        "specific_artist": specific_artist,
        "artist_albums": artist_albums,
    }
    return render(request, "tunes_app/artist_detail.html", context)

def album_detail(request, id):
    specific_album = get_object_or_404(Album, pk=id)
    album_tracks = specific_album.track_set.all()

    context = {
        "specific_album": specific_album,
        "album_tracks": album_tracks,
    }
    return render(request, "tunes_app/album_detail.html", context)

def artist_list(request):
    artists = Artist.objects.all()

    context = {
        "artists": artists,
    }
    return render(request, "tunes_app/artist_list.html", context)

def genre_list(request):
    genres = Genre.objects.all()

    context = {
        "genres": genres,
    }
    return render(request, "tunes_app/genre_list.html", context)

core/templates/core/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %}
TUNES
        {% endblock title %}
    </title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'core/styles.css' %}" />
</head>
<body>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
                <a href="{% url 'core:index' %}" class="navbar-brand">
                    TUNES UP IN YA
                    </a>
            </div>
          </div>
        </nav>
    </header>
    <div class="container">
    {%  block content %}

    {%  endblock content %}
    </div>
    <footer class="page-footer">
        <hr>
        <div class="container">
            &copy; Metropolitan Numeric 2016
        </div>
    </footer>

    <script   src="https://code.jquery.com/jquery-3.1.0.min.js"   integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="   crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}


{% block content %}
    <h2>Libraries Nav-Bar</h2>
    <hr>
    <a href="{% url 'music:album_list' %}">Albums Library</a>
    <a href="{% url 'music:artist_list' %}">Artists</a>
    <a href="{% url 'music:genre_list' %}">Genres</a>
{% endblock %}

tunes_app/templates/tunes_app/album_detail.html
{% extends "core/base.html" %}

{% block content %}
<h2>{{specific_album.name|title}}</h2>
<hr>
{% if album_tracks %}
    {% for track in album_tracks %}

        {{track.name}}<br>

    {% endfor %}
{% else %}
There are no tracks in this album.
{% endif %}
<hr>
{% endblock content %}

tunes_app/templates/tunes_app/album_list.html
{% extends "core/base.html" %}

{% block content %}
<h2>Nav-bar</h2>
<hr>
<!-- albums is in context w/in def albums_list-->
{% if albums %}
    <h2>Album Library</h2>

    {% for album in albums %}
    <a href="{% url 'music:album_detail' album.pk %}">
        {{album.name}}<br>
    </a>
    {% endfor %}
{% endif %}

<hr>
{% endblock content %}

tunes_app/templates/tunes_app/album_tracks.html
{% extends "core/base.html" %}

{% block content %}
<h2>{{specific_album.name|title}}</h2>
<hr>
{% if album_tracks %}
    {% for track in album_tracks %}

        {{track.name}}<br>

    {% endfor %}
{% else %}
There are no tracks in this album.
{% endif %}
<hr>
{% endblock content %}

tunes_app/templates/tunes_app/albums_for_artist.html
{% extends "core/base.html" %}

{% block content %}
    {% if specific_artist %}
        <h2>{{specific_artist}}</h2>
        {% for album in artist_albums %}

        {{album.name}}

        {% endfor %}
    {% endif %}

{% endblock %}

tunes_app/templates/tunes_app/albums_list.html
{% extends "core/base.html" %}

{% block content %}
<h2>Nav-bar</h2>
<hr>
<!-- albums is in context w/in def albums_list-->
{% if albums %}
    <h2>Album Library</h2>

    {% for album in albums %}
    <a href="{% url 'album:tracks_in_album' album.pk %}">
        {{album.name}}<br>
    </a>
    {% endfor %}
{% endif %}

<hr>
{% endblock content %}

tunes_app/templates/tunes_app/artist_detail.html
{% extends "core/base.html" %}

{% block content %}
    {% if specific_artist %}
        <h2>{{specific_artist}}</h2>
        {% for album in artist_albums %}

        {{album.name}}

        {% endfor %}
    {% endif %}

{% endblock %}

tunes_app/templates/tunes_app/artist_list.html
{% extends "core/base.html" %}

{% block content %}
<h2>Artists</h2>
<hr>
    {% for artist in artists %}

    <a href="{% url 'music:artist_detail' artist.pk %}">
        {{artist.name}}<br>
    </a>
    {% endfor %}

<hr>
{% endblock content %}

tunes_app/templates/tunes_app/artists_list.html
{% extends "core/base.html" %}

{% block content %}
<h2>Artists</h2>
<hr>
    {% for artist in artists %}

    <a href="{% url 'artist:albums_for_artist' artist.pk %}">
        {{artist.name}}<br>
    </a>
    {% endfor %}

<hr>
{% endblock content %}

tunes_app/templates/tunes_app/genre_list.html
{% extends "core/base.html" %}

{% block content %}
<h2>Genres</h2>
<hr>
<!-- albums is in context w/in def albums_list-->
    {% for genre in genres %}

        {{genre.name}}<br>
    </a>
    {% endfor %}

<hr>
{% endblock content %}

tunes_app/templates/tunes_app/genres_list.html
{% extends "core/base.html" %}

{% block content %}
<h2>Genres</h2>
<hr>
<!-- albums is in context w/in def albums_list-->
    {% for genre in genres %}

        {{genre.name}}<br>
    </a>
    {% endfor %}

<hr>
{% endblock content %}